"use client";

import { useState } from "react";
import { Check, Copy, Download } from "lucide-react";

export type CveReportData = {
  cveId: string;
  description: string | null;
  cvssV3: number | null;
  cvssV4: number | null;
  epssScore: number | null;
  knownExploited: boolean;
  kevDateAdded: string | null;
  publishedAt: string | null;
  vendorRefs: string[];
  actors: { name: string; confidence: number }[];
  campaigns: { name: string; status: string }[];
  reports: { title: string; id: string }[];
  news: { title: string; source: string; date: string }[];
};

function buildMarkdown(d: CveReportData): string {
  const lines: string[] = [];
  lines.push(`# ${d.cveId}`);
  if (d.knownExploited) lines.push(`\n**⚠ CISA Known Exploited Vulnerability**${d.kevDateAdded ? ` — added ${d.kevDateAdded}` : ""}`);
  lines.push(`\n## Description\n`);
  lines.push(d.description ?? "No description available.");

  lines.push(`\n## Scoring\n`);
  lines.push(`| Metric | Value |`);
  lines.push(`|---|---|`);
  lines.push(`| CVSS v3 | ${d.cvssV3 != null ? d.cvssV3.toFixed(1) : "Not scored"} |`);
  lines.push(`| CVSS v4 | ${d.cvssV4 != null ? d.cvssV4.toFixed(1) : "Not scored"} |`);
  lines.push(
    `| EPSS (30-day exploit probability) | ${d.epssScore != null ? `${(d.epssScore * 100).toFixed(2)}%` : "Not scored"} |`,
  );
  lines.push(`| CISA KEV | ${d.knownExploited ? "Yes" : "No"} |`);
  lines.push(`| Published | ${d.publishedAt ?? "Unknown"} |`);

  if (d.actors.length > 0 || d.campaigns.length > 0) {
    lines.push(`\n## Attribution\n`);
    for (const a of d.actors) lines.push(`- Actor: **${a.name}** (confidence ${a.confidence}%)`);
    for (const c of d.campaigns) lines.push(`- Campaign: **${c.name}** (${c.status})`);
  }

  if (d.reports.length > 0) {
    lines.push(`\n## Related analyst reports\n`);
    for (const r of d.reports) lines.push(`- ${r.title}`);
  }

  if (d.news.length > 0) {
    lines.push(`\n## Media coverage\n`);
    for (const n of d.news) lines.push(`- ${n.title} — ${n.source}, ${n.date}`);
  }

  if (d.vendorRefs.length > 0) {
    lines.push(`\n## References\n`);
    for (const ref of d.vendorRefs) lines.push(`- ${ref}`);
  }

  lines.push(`\n---\n_Generated by Pulse Intelligence · ${new Date().toISOString().slice(0, 10)}_`);
  return lines.join("\n");
}

export function CveReportActions({ data }: { data: CveReportData }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(buildMarkdown(data));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const md = buildMarkdown(data);
    const blob = new Blob([md], { type: "text/markdown;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${data.cveId}-report.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex shrink-0 items-center gap-2">
      <button
        type="button"
        onClick={handleCopy}
        className="inline-flex items-center gap-1.5 rounded-md border border-line bg-surface px-3 py-2 text-sm text-ink transition-colors hover:bg-surface-2"
      >
        {copied ? <Check className="size-3.5 text-ok" /> : <Copy className="size-3.5" />}
        {copied ? "Copied" : "Copy report"}
      </button>
      <button
        type="button"
        onClick={handleDownload}
        className="inline-flex items-center gap-1.5 rounded-md border border-line bg-surface px-3 py-2 text-sm text-ink transition-colors hover:bg-surface-2"
      >
        <Download className="size-3.5" />
        Export .md
      </button>
    </div>
  );
}
