import { createHash } from "node:crypto";
import type { EnrichmentProvider, LookupResult } from "@/lib/enrichment/types";
import { verdictFromScore } from "@/lib/enrichment/types";

/**
 * Deterministic fake provider.
 *
 * Exists so the whole pipeline — queue, limiter, cache, UI — can be built and
 * tested with no API keys and no network. Derives a stable score from a hash of
 * the value, so the same indicator always gets the same verdict and tests are
 * reproducible.
 *
 * Only enabled when ENABLE_STUB_PROVIDER=1, so it can never quietly contribute
 * fabricated verdicts to real intelligence.
 */
export const stubProvider: EnrichmentProvider = {
  name: "stub",
  label: "Stub (synthetic)",
  quota: {},
  ttlMs: 60 * 60 * 1000,

  supports() {
    return true;
  },

  isConfigured() {
    return process.env.ENABLE_STUB_PROVIDER === "1";
  },

  async lookup(value, type): Promise<LookupResult> {
    const hash = createHash("sha256").update(`${type}:${value}`).digest();
    const score = hash[0] % 101;
    return {
      verdict: verdictFromScore(score),
      score,
      raw: { synthetic: true, note: "Generated by the stub provider, not real intelligence." },
    };
  },
};
